/*

 BACKGROUND_ONE_M_B.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 18
   Tile set      : C:\Users\7319a\Desktop\ggj_2020_gameboy_platformer\placeholder\GameBoy Tile Designer\Platformer Sprites.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define background_one_mapWidth 32
#define background_one_mapHeight 18
#define background_one_mapBank 0

extern const char background_one_map[];

/* End of BACKGROUND_ONE_M_B.H */
