/*

 LONGSKATEBACKGROUND.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 200
   Tile set      : C:\Users\mattm\dev\c\gameboy\ggj_2020_gameboy_platformer\misc_assets\BackgroundTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define LongSkateBackgroundWidth 20
#define LongSkateBackgroundHeight 200
#define LongSkateBackgroundBank 0

extern const char LongSkateBackground[];

/* End of LONGSKATEBACKGROUND.H */
